In [9]:
import pandas as pd
import numpy as np

In [6]:
s = pd.Series(data = [1, 2], index = ['one', 'two'], name = 'Numbers', dtype = float)
s

one    1.0
two    2.0
Name: Numbers, dtype: float64

In [8]:
s + 2

one    3.0
two    4.0
Name: Numbers, dtype: float64

In [10]:
np.exp(s)

one    2.718282
two    7.389056
Name: Numbers, dtype: float64

In [11]:
s[s > 1]

two    2.0
Name: Numbers, dtype: float64

In [15]:
s

one    1.0
two    2.0
Name: Numbers, dtype: float64

In [19]:
df = pd.DataFrame(data = {'col_1':[1, 2],
                          'col_2':[22,3]}, index = ['one', 'two'])
df

     col_1  col_2
one      1     22
two      2      3

In [18]:
df.col_1

0    1
1    2
Name: col_1, dtype: int64

In [108]:
df = pd.read_csv('winemag-data-130k-v2.csv')

In [23]:
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [24]:
df.tail()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [25]:
df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

In [31]:
df.describe(include = 'all')

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
count,129971.000000,129908,129971,92506,129971.000000,120975.000000,129908,108724,50511,103727,98758,129971,129970,129971
unique,NaN,43,119955,37979,NaN,NaN,425,1229,17,19,15,118840,707,16757
top,NaN,US,"Cigar box, café au lait, and dried tobacco aro...",Reserve,NaN,NaN,California,Napa Valley,Central Coast,Roger Voss,@vossroger,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,Pinot Noir,Wines & Winemakers
freq,NaN,54504,3,2009,NaN,NaN,36247,4480,11065,25514,25514,11,13272,222
mean,64985.000000,NaN,NaN,NaN,88.447138,35.363389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,37519.540256,NaN,NaN,NaN,3.039730,41.022218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,80.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,32492.500000,NaN,NaN,NaN,86.000000,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,64985.000000,NaN,NaN,NaN,88.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,97477.500000,NaN,NaN,NaN,91.000000,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,129970.000000,NaN,NaN,NaN,100.000000,3300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [33]:
df.country

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [39]:
df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [35]:
# iloc , loc

In [42]:
# iloc [row , col]

df.iloc[[1, 2, 3], :]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian

In [65]:
df.loc[0, ['price']]

price    NaN
Name: 0, dtype: object

In [60]:
df.loc[ (df['country'] == 'Portugal') & (df['points'] > 90)]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
151,151,Portugal,"This bottling shows a rich, wood-aged wine, fu...",Gerações Colheita Seleccionada Branco,91,30.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Herdade Grande 2014 Gerações Colheita Seleccio...,Portuguese White,Herdade Grande
157,157,Portugal,"From an estate in the south of the Alentejo, t...",Grande Reserva Tinto,91,26.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Casa Santa Vitória 2013 Grande Reserva Tinto R...,Portuguese Red,Casa Santa Vitória
473,473,Portugal,"A powerful wine, richly structured and full of...",Gerações Colheita Seleccionada,92,34.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Herdade Grande 2010 Gerações Colheita Seleccio...,Portuguese Red,Herdade Grande
642,642,Portugal,This is a new wine from the hands of master wi...,Monte de Carrapatelo Colheita Seleccionada Tinto,92,30.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Luis Duarte 2013 Monte de Carrapatelo Colheita...,Portuguese Red,Luis Duarte
646,646,Portugal,As its name suggests this is a selection of ba...,Lagoalva Barrel Selection Tinto,92,23.0,Tejo,NaN,NaN,Roger Voss,@vossroger,Quinta da Lagoalva de Cima 2013 Lagoalva Barre...,Portuguese Red,Quinta da Lagoalva de Cima
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129130,129130,Portugal,Bual is the grape that creates the medium-swee...,Colheita,93,NaN,Madeira,NaN,NaN,Roger Voss,@vossroger,Cossart Gordon 1995 Colheita Bual (Madeira),Bual,Cossart Gordon
129671,129671,Portugal,"Two classic Dão grapes, Touriga Nacional and T...",Dona Georgina,93,60.0,Dão,NaN,NaN,Roger Voss,@vossroger,Quinta de Lemos 2010 Dona Georgina Red (Dão),Portuguese Red,Quinta de Lemos
129680,129680,Portugal,Old vines in a field blend give a rich structu...,Monte Cascas Grande Reserva,93,39.0,Douro,NaN,NaN,Roger Voss,@vossroger,Casca Wines 2011 Monte Cascas Grande Reserva R...,Portuguese Red,Casca Wines
129685,129685,Portugal,The red-juice grape Alicante Bouschet gives a ...,Comporta,93,50.0,Península de Setúbal,NaN,NaN,Roger Voss,@vossroger,Herdade da Comporta 2010 Comporta Alicante Bou...,Alicante Bouschet,Herdade da Comporta
129901,129901,Portugal,Wood fermentation and aging have given this fi...,NaN,91,30.0,Beira Atlantico,NaN,NaN,Roger Voss,@vossroger,Quinta de Foz de Arouce 2015 Cerceal (Beira At...,Cerceal,Quinta de Foz de Arouce

In [61]:
df['New_col'] = 0
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,New_col
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,0
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,0
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,0
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,0
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,0

In [62]:
# df.loc[ condition , col_name u want to affect] = value

df.loc[df['points'] > 90, 'New_col'] = 1

In [64]:
df.loc[df['points'] > 90]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,New_col
119,119,France,Medium-gold in color. Complex and inviting nos...,Schoenenbourg Grand Cru Vendanges Tardives,92,80.0,Alsace,Alsace,NaN,NaN,NaN,Dopff & Irion 2004 Schoenenbourg Grand Cru Ven...,Riesling,Dopff & Irion,1
120,120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto,1
121,121,US,The vineyard is one of the better Chardonnay s...,Stuhlmuller Vineyard,92,36.0,California,Alexander Valley,Sonoma,NaN,NaN,Matrix 2007 Stuhlmuller Vineyard Chardonnay (A...,Chardonnay,Matrix,1
122,122,US,Defines Rockpile Zinfandel in intensity of fru...,Rockpile Cemetary Vineyard,92,39.0,California,Rockpile,Sonoma,NaN,NaN,Mauritson 2007 Rockpile Cemetary Vineyard Zinf...,Zinfandel,Mauritson,1
123,123,Australia,The blend is roughly two-thirds Shiraz and one...,Parson's Flat,92,40.0,South Australia,Padthaway,NaN,Joe Czerwinski,@JoeCz,Henry's Drive Vignerons 2006 Parson's Flat Shi...,Shiraz-Cabernet Sauvignon,Henry's Drive Vignerons,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129936,129936,France,A blend from several premier cru vineyards in ...,Premier Cru,91,66.0,Burgundy,Pommard,NaN,Roger Voss,@vossroger,Bouchard Père & Fils 2005 Premier Cru (Pommard),Pinot Noir,Bouchard Père & Fils,1
129937,129937,Austria,"Smooth, creamy aromas are followed by a rich, ...",Langenloiser Berg-Vogelsang,91,32.0,Kamptal,NaN,NaN,Roger Voss,@vossroger,Bründlmayer 2007 Langenloiser Berg-Vogelsang G...,Grüner Veltliner,Bründlmayer,1
129938,129938,Argentina,Compared to the regular 2006 Malbec from Chaka...,Reserve,91,25.0,Mendoza Province,Luján de Cuyo,NaN,Michael Schachner,@wineschach,Chakana 2006 Reserve Malbec (Luján de Cuyo),Malbec,Chakana,1
129939,129939,Austria,"A true TBA, its very rich, toffee-flavored, in...",Grand Vin,91,70.0,Burgenland,NaN,NaN,Roger Voss,@vossroger,Schloss Halbturn 2004 Grand Vin White (Burgenl...,White Blend,Schloss Halbturn,1
129940,129940,US,This is the winery's bells and whistles Chardo...,Watson Vineyard,91,36.0,California,Mendocino,NaN,NaN,NaN,Standish 2006 Watson Vineyard Chardonnay (Mend...,Chardonnay,Standish,1

In [70]:
df.rename(columns = {"Country" : "country"}, inplace = True)

In [71]:
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,New_col
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,0
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,0
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,0
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,0
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,0

In [92]:
df.isnull().mean() * 100

Unnamed: 0                0.000000
country                   0.000000
description               0.000000
designation              28.825661
points                    0.000000
price                     6.921544
province                  0.048472
region_1                 16.347493
taster_name              20.192197
taster_twitter_handle    24.015357
title                     0.000000
variety                   0.000769
winery                    0.000000
New_col                   0.000000
dtype: float64

In [75]:
df.drop(columns = ['region_2'], inplace = True)

In [77]:
# numeric , # categorical
# mean          mode
# mode
# median

In [91]:
x = pd.Series(data = [1, 1, 1, 1, 2, 3, 4, 5, 4, 6, 6, 6, 6])

x.mode()

0    1
1    6
dtype: int64

In [87]:
df['country'].fillna(df['country'].mode()[0], inplace = True)

In [94]:
df['country'].mode()

0    US
dtype: object

In [95]:
df['country'].unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', 'Turkey', 'Czech Republic', 'Slovenia', 'Luxembourg',
       'Croatia', 'Georgia', 'Uruguay', 'England', 'Lebanon', 'Serbia',
       'Brazil', 'Moldova', 'Morocco', 'Peru', 'India', 'Bulgaria',
       'Cyprus', 'Armenia', 'Switzerland', 'Bosnia and Herzegovina',
       'Ukraine', 'Slovakia', 'Macedonia', 'China', 'Egypt'], dtype=object)

In [106]:
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,New_col
0,0,3.0,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,89,NaN,Sicily & Sardinia,Etna,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,0
1,1,2.0,"This is ripe and fruity, a wine that is smooth...",Avidagos,89,15.0,Douro,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,0
2,2,1.0,"Tart and snappy, the flavors of lime flesh and...",NaN,89,14.0,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,0
3,3,1.0,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,89,13.0,Michigan,Lake Michigan Shore,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,0
4,4,1.0,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,89,65.0,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,0

In [103]:
df.points = df.points.map(lambda x: x + 1)

In [104]:
# l = ['a', 'b', 'c']

# for i, v in enumerate(l):
#     print(i, v)

0 a
1 b
2 c

In [105]:
country_mapping = {"US" : 1, "Portugal":2, "Italy":3}
df.country = df.country.map(country_mapping)

In [109]:
df.country.value_counts()

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Macedonia                    12
Serbia                       12
Czech Republic               12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
Egypt                         1
China                         1
Name: country, dtype: int64

In [118]:
df.groupby('country').points

0         87
1         87
2         87
3         87
4         87
          ..
81814     89
83622     90
96759     88
109989    89
110246    84
Name: points, Length: 202, dtype: int64

In [119]:
df1 = pd.read_csv('winemag-data-130k-v2.csv')
df2 = pd.read_csv('winemag-data-130k-v2.csv')
df3 = pd.concat([df1,df2])

In [120]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 259942 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             259942 non-null  int64
 1   country                259816 non-null  object
 2   description            259942 non-null  object
 3   designation            185012 non-null  object
 4   points                 259942 non-null  int64
 5   price                  241950 non-null  float64
 6   province               259816 non-null  object
 7   region_1               217448 non-null  object
 8   region_2               101022 non-null  object
 9   taster_name            207454 non-null  object
 10  taster_twitter_handle  197516 non-null  object
 11  title                  259942 non-null  object
 12  variety                259940 non-null  object
 13  winery                 259942 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 29.7+ MB

In [121]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

In [122]:
'''
read_csv
describe
info
iloc
loc
sort_values
isnull
fillna
drop
groupby
rename
to_csv
dropna
'''

'\nread_csv\ndescribe\ninfo\niloc\nloc\nsort_values\nisnull\nfillna\ndrop\ngroupby\nrename\nto_csv\ndropna\n'

In [123]:
df3.to_csv('new_data.csv')